package org.firebears.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.firebears.Robot;
import org.firebears.RobotMap;
import org.firebears.subsystems.PidRobotDrive;

/**
 *
 */
public class DriveCommand extends Command {
	public DriveCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.chassis);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	protected void initialize() {
	}

	protected void execute() {
		//Make sure not in PID Mode******
		if (!(RobotMap.chassisRobotDrive instanceof PidRobotDrive)) {
			double forward = Robot.oi.joystickDrive.getY();
			if (forward >= 0.05) {
				double percentDrive = forward / 0.95;
				double powerDrive = percentDrive * 0.7;
				forward = powerDrive + 0.3;
			} else if (forward <= -0.05) {
				double percentDrive = forward / 0.95;
				double powerDrive = percentDrive * 0.7;
				forward = powerDrive - 0.3;
			}
			// TODO drive dead zone and squared output (non-PID) Where are we
			// with non-inuitive reverse?

			Robot.chassis.move(forward, Robot.oi.joystickDrive.getX());
		}
		// PID Drive
		else
			Robot.chassis.move(Robot.oi.joystickDrive.getY(),
					Robot.oi.joystickDrive.getX());

	}

	protected boolean isFinished() {
		return false;
	}

	protected void end() {
	}

	protected void interrupted() {
	}
}
