
package org.firebears.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.firebears.Robot;
/**
 *
 */
public class  ShiftDownCommand extends Command {
    public ShiftDownCommand() {
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
    }
    protected void execute() {
        Robot.chassis.chassisShiftDown();
    }
    protected boolean isFinished() {
        return true;
    }
 
    protected void end() {
    }
    protected void interrupted() {
    }
}
